name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy_dev:
    name: Deploy Application in develop environment
    runs-on: develop
    environment: env

    steps:
      - name: Clean .next directory
        run: |
          rm -rf $GITHUB_WORKSPACE/.next

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          echo "SECRET_JWT=${{ secrets.SECRET_JWT }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          echo "WORKSPACE_MONGO_URL=${{ secrets.WORKSPACE_MONGO_URL }}" >> .env
          echo "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" >> .env

      - name: Deploy Application
        run: |
          echo "Starting deployment..."
          docker compose up -d --build

      - name: Clean up old Docker images
        run: |
          docker image prune -a -f
          docker system prune -a --volumes -f
          docker volume prune -f
